### ISSUE TITLE
About development workflows

### ISSUE THREAD

**Issue by getvega** [samuelneff/sequelize-auto-ts#2]
Hi - this module looks great for bootstrapping a project from scratch, but how well does it scale with the project itself? For instance, how can I add instance / class methods without touching at the generated files?

It would be great if it could generate base classes and let higher level classes to be edited. For instance `User (can be edited) -› BaseUser (generated)`

**Comment by samuelneff** [comment]
It can definitely be used in very large projects. However, I will say that I created this project for my personal use and as I've needed to I made changes to the generators, so it's not as extensible as it would be if my true original intent was to make it totally reusable. I'm happy to make changes though if people find it useful.

I don't think supporting user-provided base classes is an option. For the `*Instance` classes, they are instantiated by Sequelize and have a Sequelize defined base classes. For `*Pojo` classes, they are specifically made to separate data and functionality so they can be safely sent over the wire (to/from json). 

Sequelize does support injecting custom methods and properties into the `*Instance` classes (both the static models and the instances) and I do that for some helper methods. I would not be too difficult to support some kind of source file(s) that provided a template for methods to inject and then include those in the generated code. To do this I would specify a file format and upon generation look for, parse, and include methods from this file.

Another option is I could allow for an optional `extensions` object to provided to the `initialize()` method and then mix any class and instance methods/properties from this object into each of the models/instances. That would probably be easier for me and the user.

Comments? What specific type of functionality are you looking to add?

Also note that in my personal use, I have a lot of utility methods that I use to wrap the Sequelize methods. I generally prefer to do this rather then add them directly to the Sequelize models/instances to keep things separate and also because I do want to keep some separation between my custom code and `sequelize-auto-ts` (since I now know that some other people use it--thank you!).

When I get to writing up real documentation for `sequelize-auto-ts` (sorry, personal project, will get to it some time), I'll also include the utility methods I wrote up as extras.

**Comment by getvega** [comment]
Thank you for your reply.

Yeah I understand that POJOs need to stay as pure as possible - however in my personal experience, I like to enrich a lot both Instance (`invoice.computePrice()` or `user.getFullname()`) and Static classes (`Invoice.findUnpaidForUser(user: UserInstance)`).

If I understand you correctly, if I don't want to edit the generated files, I would need here to have a `UserHelper` and `UsersHelper` or `UserStaticHelper`).
Using as you say an "extension" file could also do the trick, but I find that much less OO...

**Comment by samuelneff** [comment]
I wasn't saying to create `*Helper*` classes. I'm saying that's an option, but usually better for more generic things, not specific to one instance type. When I have time I'll look into a way to allow custom extensions.
