### ISSUE TITLE
Question: Why not generate interfaces based on sequelize definitions?

### ISSUE THREAD

**Issue by paulkoerbitz** [samuelneff/sequelize-auto-ts#9]
First of all many thanks for the development of sequelize-auto-ts - I would love to use it ;) The reason that I can't use it right now is that we use postrgres as our database, so I think we would need to write a new schema dialect layer. 

I was wondering why one wouldn't base the generation of interfaces directly - after all that's what most (all?) users of sequelize already have and it is what sequelize is drawing all its information from? Could this be a way to avoid having special code for every db or is this a bad idea?

**Comment by samuelneff** [comment]
The reason I pull from the database is precisely because I do not have the sequelize definitions. `sequelize-auto-ts` provides to features.. it creates interfaces for all your table definitions, and it creates sequelize model definitions. sequelize itself is based around model first which admittedly is the direction most ORMs have gone. I'm more traditional and prefer to work on my schema in my database, not in my model, and thus I created a tool to support database first with sequelize.

There were other people interested in Postgres too and I think one of them started working on a patch but never got it done or submitted. I'm too busy now to do it myself, since I don't have a personal need, but if someone comes up with one that works transparently I'll be happy to merge it.

Thanks,

Sam

**Comment by paulkoerbitz** [comment]
Hi Sam,

thank you for explaining the reasons. I understand better now and know the time constraints you speak about all too well. I'll have a look at generating interfaces from sequelize definitions (not making any promises here...). 

Thank you
Paul

**Comment by samuelneff** [comment]
Sure, shouldn't be all that difficult, but that's usually the last word of any software developer before jumping down some bottomless rabbit hole, right?

Anyways, `sequelize-auto-ts` defines an object model for storing the schema definition and builds this up from the schema defined in the database. If you build the same object model from existing sequelize definitions, then you can use the rest of `sequelize-auto-ts` as is.

HTH,

Sam

**Comment by paulkoerbitz** [comment]
Yeah, famous last words ;) OK, it does sound manageable indeed, the one
problem is that I don't know how sequelize represents its definitions, so I
guess I have to figure that out ;)

Anyway, thanks for your input - if I manage to get this going I'll let you
know.
